# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Figma MCP PRO
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json package-lock.json .
RUN npm ci --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and production dependencies
COPY --from=builder /app/package.json /app/package-lock.json ./
COPY --from=builder /app/dist ./dist

# Install only production dependencies
RUN npm ci --only=production --ignore-scripts

# Default workdir and entrypoint
ENV NODE_ENV=production

ENTRYPOINT ["node", "dist/index.js"]
CMD ["--figma-api-key", "${FIGMA_API_KEY}"]
